### ISSUE TITLE
Release checklist (for real this time)

### ISSUE THREAD

**Issue by christopher-dG** [Xh4H/Discord.jl#12]
- [ ] Update `@command` to be friendlier
- [ ] Examples up to date
- [ ] Tutorial up to date and maybe different/better (notebook would be a nice format)
- [ ] Some more tests for handlers and commands, if I don't feel too lazy

**Comment by Xh4H** [comment]
I would prefer to stick to allowing only bots. Discord made some effort to hide user's tokens so that they could not automize their account.

**Comment by christopher-dG** [comment]
Sounds good, maybe we can reconsider when Julia becomes the standard web programming language :joy:
